name: "Deploy"

on:
  push:
    branches:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  VCPKG_CACHE_DIR: "~/.vcpkg/cache"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: "dependencygraph"

permissions:
  contents: "write"

jobs:
  publish:
    runs-on: "windows-latest"
    strategy:
      fail-fast: true
      matrix:
        build-config: ["Debug", "Release"]
        arch: ["x64", "x86"]
        path: ["bin/*.dll, bin/*.pdb", "bin/*.dll"]

    env:
      archive-path: swp-loader-${{ github.ref_name }}-${{ matrix.build-config }}-${{ matrix.arch }}${{ contains(matrix.path, '.pdb') && '-WithDebugSymbols' || '' }}.zip

    name: "Build a ${{ matrix.build-config }} (${{ matrix.arch }} | ${{ matrix.path }}) version"
    steps:
      - name: "Print Archive name"
        run: "echo ${{ env.archive-path }}"

      - name: "Checkout"
        uses: "actions/checkout@main"
        with:
          submodules: true

      - name: "Add MSBuild to PATH"
        uses: "microsoft/setup-msbuild@main"

      - name: "Integrate vcpkg"
        run: "vcpkg integrate --dry-run install"

      - name: "Cache VCPKG packages"
        uses: "actions/cache@main"
        with:
          key: "${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}"
          path: "${{ env.VCPKG_CACHE_DIR }}"

      - name: "Build solution"
        run: "msbuild /m /p:Configuration=${{ matrix.build-config }} /property:Platform=${{ matrix.arch }} /property:VcpkgInstalledDir=${{ env.VCPKG_CACHE_DIR }}"

      - name: "Pack to archive"
        run: "Compress-Archive -Path ${{ matrix.path }} -DestinationPath ${{ env.archive-path }}"

      - name: "Files in workplace"
        run: "ls ${{ github.workspace }}"

      - name: "Publish build"
        uses: "softprops/action-gh-release@master"
        with:
          name: "SoulWorker Plugin Loader ${{ github.ref_name }}"
          files: ${{ env.archive-path }}
          generate_release_notes: true
          tag_name: "${{ github.ref_name }}"
