name: Deploy

on:
  push:
    branches:
    - main

env:
  VERSION: 1.0.${{ github.run_attempt }}-${{ github.run_number }}

jobs:
  update-version:
    if: "!contains(github.event.head_commit.message, 'Apply automatic changes')"
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v3.0.0
      with:
        submodules: true
        token: ${{ secrets.PAT }}
        ref: main
        fetch-depth: 0
        
    - name: Update version (script)
      working-directory: .github/scripts
      run: ./UpdateVersion.ps1
      shell: pwsh

    - name: Push to SDK repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        repository: swp-sdk
        
    - name: Push to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main 

  publish:
    if: "!contains(github.event.head_commit.message, 'Apply automatic changes')"
    runs-on: windows-latest
    needs: update-version
    strategy:
      matrix: 
        include:
          - BUILD_CONFIGURATION: Debug
            PATHS: output/*.dll, output/*.pdb 
            
          - BUILD_CONFIGURATION: Release
            PATHS: output/*.dll
    name: ${{ matrix.BUILD_CONFIGURATION }}
    steps:          
    - name: Checkout
      uses: actions/checkout@v3.0.0
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Build solution
      run: msbuild /m /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} /property:Platform=x86
      
    - name: Pack to archive
      run: Compress-Archive -Path ${{ matrix.PATHS }} -DestinationPath swp-loader-${{ env.VERSION }}-${{ matrix.BUILD_CONFIGURATION }}.zip

    - name: Publish build
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: swp-loader-${{ env.VERSION }}-${{ matrix.BUILD_CONFIGURATION }}.zip
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
