name: Deploy

on:
  push:
    branches:
      - 'v[\d].[\d].[\d]'

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix: 
        include:
          - BUILD_CONFIGURATION: Debug
            PATHS: bin/*.dll, bin/*.pdb

          - BUILD_CONFIGURATION: Release
            PATHS: bin/*.dll

    name: Build a ${{ matrix.BUILD_CONFIGURATION }} version
    steps: 
    - name: Checkout
      uses: actions/checkout@main
      with: 
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Integrate vcpkg
      run: vcpkg integrate install
      
    - name: Build solution
      run: msbuild /m /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} /property:Platform=x86

    - name: Pack to archive
      run: Compress-Archive -Path ${{ matrix.PATHS }} -DestinationPath swp-loader-v${{ github.ref_name }}-${{ matrix.BUILD_CONFIGURATION }}.zip

    - name: Publish build
      uses: softprops/action-gh-release@master
      with:
        name: SoulWorker Plugin Loader v${{ github.ref_name }}
        files: swp-loader-v${{ github.ref_name }}-${{ matrix.BUILD_CONFIGURATION }}.zip
        generate_release_notes: true