name: Deploy

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  VCPKG_CACHE_DIR: ~/.vcpkg/cache

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix: 
        include:
          - BUILD_CONFIGURATION: Debug
            PATHS: bin/**/.dll, bin/**/.pdb

          - BUILD_CONFIGURATION: Release
            PATHS: bin/**/.dll

    name: Build a ${{ matrix.BUILD_CONFIGURATION }} version
    steps: 
    - name: Checkout
      uses: actions/checkout@main
      with: 
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Integrate vcpkg
      run: vcpkg integrate install
      
    - name: Cache VCPKG packages
      uses: actions/cache@main
      with:
        key: vcpkg
        path: ${{ env.VCPKG_CACHE_DIR }}

    - name: Build solution
      run: msbuild /m /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} /property:Platform=x86 /property:VcpkgInstalledDir=${{ env.VCPKG_CACHE_DIR }}

    - name: Pack to archive
      run: Compress-Archive -Path ${{ matrix.PATHS }} -DestinationPath swp-loader-${{ github.ref_name }}-${{ matrix.BUILD_CONFIGURATION }}.zip

    - name: Publish build
      uses: softprops/action-gh-release@master
      with:
        name: SoulWorker Plugin Loader ${{ github.ref_name }}
        files: swp-loader-${{ github.ref_name }}-${{ matrix.BUILD_CONFIGURATION }}.zip
        generate_release_notes: true
        tag_name: ${{ github.ref_name }}