name: MSBuild
on:
  push:
    branches:
    - main

env:
  SOLUTION_FILE_PATH: .
  VERSION: 1.0.0.${{ github.job_id }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest          
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - id: generate_matrix
        run: |
          ls
          chmod +x .github/workflows/generate_matrix.sh
          ./.github/workflows/generate_matrix.sh
        env: 
          VERSION: ${{ env.VERSION }}

  publish:
    runs-on: windows-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Install vcpkg
      run: "vcpkg integrate install"

    - name: Build solution
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} /property:Platform=x86 ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Pack to archive
      run: Compress-Archive -Path env.PATHS -DestinationPath ${{ matrix.FILE_NAME }}

    - name: Publish build
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.FILE_NAME }}
        tag_name: ${{ env.VERSION }}
