name: MSBuild
on:
  push:
    branches:
    - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
  VERSION: 1.0.0.${{ github.job }}-alpha

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          matrix_row() {
              echo "{\"build_target\":\"$1\",\"VERSION\":\"${VERSION}-$1\",\"FILE_NAME\":\"${VERSION}-$1.zip\"}"
          }

          debug=$(matrix_row "Debug")
          release=$(matrix_row "Release")

          MATRIX_JSON="{\"include\":[${debug},${release}]}"
          
          echo '::set-output name=matrix::${MATRIX_JSON}'
        env: 
          VERSION: ${{ env.VERSION }}
          
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  publish:
    runs-on: windows-2022
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
        
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install vcpkg
      run: "vcpkg integrate install"

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Pack output
      run: Compress-Archive -Path ${{ env.SOLUTION_FILE_PATH }}\output\*.dll -DestinationPath ${{ matrix.FILE_NAME }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.FILE_NAME }}
        tag_name: ${{ matrix.VERSION }}
